#!/usr/bin/env python3
"""Build LaTeX numbers/tables and vector figures from the synthetic results.

Run after code/nsga2_demo.py. Requires NumPy and Matplotlib only; compilation
itself uses the generated files and never executes Python.
"""
import json
import hashlib
import os
from pathlib import Path
import tempfile

os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "gmcm2026-mpl"))
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
FIGURES = ROOT / "figures"
BLUE, ORANGE, GREEN = "#0072B2", "#D55E00", "#009E73"


def tex_table(filename, caption, label, columns, headers, rows):
    text = [r"% Generated by scripts/prepare_paper.py; synthetic data.",
            r"\begin{table}[htbp]", r"  \centering",
            r"  \caption{" + caption + "}", r"  \label{" + label + "}",
            r"  \begin{tabular}{@{}" + columns + r"@{}}", r"    \toprule",
            "    " + " & ".join(headers) + r"\\", r"    \midrule"]
    text += ["    " + " & ".join(row) + r"\\" for row in rows]
    text += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    (DATA / filename).write_text("\n".join(text), encoding="utf-8")


def save(fig, name):
    # Tight bounding boxes preserve labels in both the vector and preview files.
    fig.savefig(FIGURES / (name + ".pdf"), bbox_inches="tight")
    fig.savefig(FIGURES / (name + ".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def main():
    j = json.loads((DATA / "optimization_results.json").read_text())
    selected = j["selected_solutions"]
    ref, comp = j["reference_mix"], selected["compromise"]
    low, high = selected["minimum_carbon"], selected["maximum_strength"]
    front = j["main_pareto_front"]
    delta = j["compromise_comparison_to_reference"]
    p = np.array([x["pasta_kg_m3"] for x in front])
    macros = {
        "FrontCount": str(len(front)),
        "ReferenceCount": str(j["quality_indicator"]["reference_size"]),
        "CompID": comp["solution_id"],
        "CompCarbon": f'{comp["carbon_kgCO2e_m3"]:.2f}',
        "CompCost": f'{comp["cost_CNY_m3"]:.2f}',
        "CompStrength": f'{comp["strength_MPa"]:.2f}',
        "CompSlump": f'{comp["slump_mm"]:.2f}',
        "CompPasta": f'{comp["pasta_kg_m3"]:.4f}',
        "CarbonReduction": f'{100 * delta["carbon_reduction_fraction"]:.2f}',
        "CostReduction": f'{100 * delta["cost_reduction_fraction"]:.2f}',
        "StrengthLoss": f'{-delta["strength_change_MPa"]:.2f}',
        "PastaMedian": f'{np.median(p):.4f}',
        "PastaMax": f'{max(p):.4f}',
        "SlumpMargin": f'{comp["slump_mm"] - 140:.2f}',
        "NSGAIGD": f'{j["five_run_aggregate"]["NSGA-II"]["igd_joint_empirical_reference"]["mean"]:.5f}',
        "RandomIGD": f'{j["five_run_aggregate"]["uniform_random"]["igd_joint_empirical_reference"]["mean"]:.5f}',
    }
    (DATA / "paper_values.tex").write_text(
        "% Generated from synthetic optimization_results.json.\n" +
        "% Source SHA256: " + hashlib.sha256((DATA / "optimization_results.json").read_bytes()).hexdigest() + "\n" +
        "".join("\\newcommand{\\" + name + "}{" + value + "}\n"
                for name, value in macros.items()), encoding="utf-8")

    plans = [("基准", ref), ("最低碳/成本", low), ("最高强度", high), ("折中", comp)]
    tex_table("decision_table.tex", "代表方案的决策变量（合成情景）", "tab:decisions", "lrrrr",
              ["方案", "$B$", "$s$", "$r$", "$P$"],
              [[name, f'{x["binder_kg_m3"]:.2f}', f'{x["slag_fraction"]:.4f}',
                f'{x["effective_water_binder_ratio"]:.4f}', f'{x["pasta_kg_m3"]:.4f}'] for name, x in plans])
    tex_table("performance_table.tex", "代表方案的目标值与坍落度响应（合成计算）", "tab:performance", "lrrrr",
              ["方案", "$E$", "$C_{\\mathrm{cost}}$", "$F$", "$H$"],
              [[name] + [f'{x[k]:.2f}' for k in
                ["carbon_kgCO2e_m3", "cost_CNY_m3", "strength_MPa", "slump_mm"]] for name, x in plans])
    tex_table("mass_table.tex", "代表方案的材料用量（单位：kg/m$^3$）", "tab:masses", "lrrrrr",
              ["方案", "水泥", "矿渣", "总水", "细砂", "干意面"],
              [[name] + [f'{x[k]:.2f}' for k in ["cement_kg_m3", "slag_kg_m3", "water_kg_m3", "sand_kg_m3"]]
                + [f'{x["pasta_kg_m3"]:.4f}'] for name, x in plans])
    rows = []
    for name, label in [("NSGA-II", "NSGA-II"), ("uniform_random", "均匀随机")]:
        a = j["five_run_aggregate"][name]
        vals = [a[k] for k in ["igd_joint_empirical_reference", "compromise_carbon_kgCO2e_m3",
                              "compromise_cost_CNY_m3", "compromise_strength_MPa"]]
        rows.append([label] + [f'${v["mean"]:.{5 if i == 0 else 2}f}\\pm{v["sample_std"]:.{5 if i == 0 else 2}f}$'
                               for i, v in enumerate(vals)])
    tex_table("replicate_table.tex", "五次运行的均值与样本标准差（相同评价预算）", "tab:replicates", "lrrrr",
              ["方法", "IGD", "折中 $E$", "折中成本", "折中 $F$"], rows)
    rows = []
    for v in j["sensitivity"]["absorption"]:
        rows.append([f'{v["absorption_kg_water_per_kg_dry_pasta"]:.1f}',
                     f'{v["water_kg_m3"]:.3f}', f'{v["sand_kg_m3"]:.3f}',
                     f'{v["carbon_kgCO2e_m3"]:.4f}', "满足" if v["feasible"] else "不满足"])
    tex_table("absorption_table.tex", "固定折中变量时的吸水补偿情景", "tab:absorption", "rrrrl",
              ["$a$/(kg/kg)", "$W$/(kg/m$^3$)", "$A$/(kg/m$^3$)", "$E$", "原约束"], rows)

    plt.rcParams.update({
        "font.family": "serif", "font.serif": ["Times New Roman", "DejaVu Serif"],
        "font.size": 11, "axes.labelsize": 11, "axes.titlesize": 12,
        "legend.fontsize": 10, "xtick.labelsize": 10, "ytick.labelsize": 10,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.linewidth": 0.8, "lines.linewidth": 1.7,
        "pdf.fonttype": 42, "ps.fonttype": 42,
    })
    fig, ax = plt.subplots(figsize=(6.3, 3.8), layout="constrained")
    scatter = ax.scatter([x["carbon_kgCO2e_m3"] for x in front], [x["strength_MPa"] for x in front],
                         c=[x["cost_CNY_m3"] for x in front], cmap="viridis", s=22, zorder=2)
    fig.colorbar(scatter, ax=ax, label=r"Material cost (CNY/m$^3$)", pad=0.03)
    for x, marker, color, label in [(ref, "X", ORANGE, "Reference"),
                                    (comp, "*", "black", "Compromise"),
                                    (low, "s", BLUE, "Min. carbon / cost"),
                                    (high, "^", GREEN, "Max. strength")]:
        ax.scatter(x["carbon_kgCO2e_m3"], x["strength_MPa"], marker=marker,
                   s=90 if marker == "*" else 45, c=color, edgecolors="white", linewidths=0.5,
                   zorder=3, label=label)
    ax.set(xlabel=r"Carbon (kg CO$_2$e/m$^3$)", ylabel="Synthetic strength (MPa)",
           title="Synthetic Pareto set | seed 42", xlim=(130, 420), ylim=(37, 81))
    ax.legend(loc="lower right", frameon=False)
    ax.grid(alpha=0.18)
    save(fig, "pareto")

    fig, axes = plt.subplots(1, 2, figsize=(6.4, 2.9), layout="constrained")
    h = j["main_run_history"]
    axes[0].plot([x["objective_evaluations"] for x in h], [x["minimum_carbon"] for x in h],
                 "o-", color=BLUE, markersize=3, label="NSGA-II, seed 42")
    random_min = next(x["minimum_carbon_kgCO2e_m3"] for x in j["run_summary"]
                      if x["algorithm"] == "uniform_random" and x["seed"] == 42)
    axes[0].axhline(random_min, color=ORANGE, linestyle="--", label="Random, final minimum")
    axes[0].set(xlabel="Candidate evaluations", ylabel=r"Minimum carbon (kg CO$_2$e/m$^3$)",
                title="(a) One objective extreme")
    axes[0].legend(frameon=False, fontsize=8)
    for i, (name, color) in enumerate([("NSGA-II", BLUE), ("uniform_random", ORANGE)]):
        values = [x["igd_joint_empirical_reference"] for x in j["run_summary"] if x["algorithm"] == name]
        axes[1].scatter(np.linspace(i - .09, i + .09, len(values)), values, c=color, s=25, zorder=3)
        axes[1].errorbar(i, np.mean(values), yerr=np.std(values, ddof=1), color="black", capsize=5,
                         marker="_", markersize=16, linewidth=1.2, zorder=2)
    axes[1].set(xticks=[0, 1], xticklabels=["NSGA-II", "Random"], xlim=(-.4, 1.4),
                ylim=(0, .082), ylabel="IGD (joint empirical reference)", title="(b) Five runs; lower is better")
    for ax in axes:
        ax.grid(axis="y", alpha=.18)
    save(fig, "convergence")

    fig, axes = plt.subplots(1, 2, figsize=(6.4, 2.9), layout="constrained")
    reduction = np.array([0, 5, 10])
    for x, color, marker, label in [(comp, BLUE, "o", "Compromise"), (low, ORANGE, "s", "Min. carbon")]:
        axes[0].plot(reduction, x["strength_MPa"] * (1 - reduction / 100),
                     color=color, marker=marker, label=label, markersize=4)
    axes[0].axhline(40, color="black", linestyle="--", linewidth=1, label="Constraint")
    axes[0].set(xlabel="Assumed strength reduction (%)", ylabel="Synthetic strength (MPa)",
                xticks=reduction, ylim=(34, 61), title="(a) Fixed-mix stress test")
    axes[0].legend(frameon=False, fontsize=8)
    a = j["sensitivity"]["pasta_carbon_factor"]
    axes[1].plot([x["pasta_carbon_kgCO2e_kg"] for x in a],
                 [x["carbon_kgCO2e_m3"] - comp["carbon_kgCO2e_m3"] for x in a], "o-", color=GREEN, markersize=4)
    axes[1].axhline(0, color="black", linestyle="--", linewidth=.8)
    axes[1].set(xlabel=r"Pasta factor (kg CO$_2$e/kg)", ylabel=r"Carbon change (kg CO$_2$e/m$^3$)",
                title="(b) Compromise: near-zero pasta")
    axes[1].ticklabel_format(axis="y", style="plain", useOffset=False)
    for ax in axes:
        ax.grid(alpha=.18)
    save(fig, "sensitivity")
    print("Generated paper values, 5 tables, and 3 figures (PDF + PNG, 300 dpi).")


if __name__ == "__main__":
    main()
